spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db35security
    username: root
    password: root2023
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    generate-ddl: true